#!/bin/bash
# Hugging Face Spaceへのアップロード手順

echo "=== Hugging Face Space Git Push 手順 ==="
echo ""
echo "1. Hugging Faceアクセストークンを取得"
echo "   https://huggingface.co/settings/tokens"
echo "   → 'New token' → Role: write を選択"
echo ""
echo "2. あなたのSpace URLを確認"
echo "   例: https://huggingface.co/spaces/YOUR_USERNAME/スマートメジャー背景除去"
echo ""
echo "3. 以下のコマンドを実行:"
echo ""
echo "cd /home/user/huggingface-space"
echo "git init"
echo "git add app.py requirements.txt README.md .gitignore"
echo "git commit -m 'Add withoutBG Focus app files'"
echo ""
echo "# SpaceのURLを設定（YOUR_USERNAMEを自分のユーザー名に変更）"
echo "git remote add origin https://huggingface.co/spaces/YOUR_USERNAME/スマートメジャー背景除去"
echo ""
echo "# プッシュ（アクセストークンを入力）"
echo "git push origin main"
echo ""
echo "ユーザー名: YOUR_USERNAME"
echo "パスワード: hf_xxxxxxxxxx（アクセストークン）"
echo ""
